const allProducts = [
  {
    id: 1,
    name: "تینت لب اتود هوس مدل Water Tint",
    vijegi: "رنگ: زرد،آبی،سرخابی",
    star: 4.5,
    category: "لب،لوازم آرایشی",
    brand: "پریم",
    price: 100,
    img: "images/icons/tinit.jpg",
  },
  {
    id: 2,
    name: "تینت لب اتود هوس مدل Water Tint",
    vijegi: "رنگ: زرد،آبی،سرخابی",
    star: 2.5,
    category: "لب،لوازم آرایشی",
    brand: "پریم",
    price: 1000,
    img: "images/icons/rojegone.jpg",
  },
  {
    id: 3,
    name: "تینت لب اتود هوس مدل Water Tint",
    vijegi: "رنگ: زرد،آبی،سرخابی",
    star: 4,
    category: "شامپو",
    brand: "پریم",
    price: 150,
    img: "images/icons/shampooop.jpg",
  },
  {
    id: 3,
    name: "تینت لب اتود هوس مدل Water Tint",
    vijegi: "رنگ: زرد،آبی،سرخابی",
    star: 4,
    category: "شامپو",
    brand: "پریم",
    price: 150,
    img: "images/icons/shampooop.jpg",
  },
  {
    id: 3,
    name: "تینت لب اتود هوس مدل Water Tint",
    vijegi: "رنگ: زرد،آبی،سرخابی",
    star: 4,
    category: "شامپو",
    brand: "پریم",
    price: 150,
    img: "images/icons/shampooop.jpg",
  },
];
